# Generated by Django 6.0.5 on 2026-05-25 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP (fuel & procurement)'), ('utility', 'Utility (electricity)'), ('travel', 'Corporate travel')], max_length=20)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial success')], default='processing', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('suspicious_count', models.PositiveIntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP (fuel & procurement)'), ('utility', 'Utility (electricity)'), ('travel', 'Corporate travel')], max_length=20)),
                ('source_row_id', models.CharField(blank=True, max_length=100)),
                ('scope', models.CharField(choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3')], max_length=1)),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('procurement', 'Procurement'), ('electricity', 'Electricity'), ('flight', 'Flight'), ('hotel', 'Hotel'), ('ground', 'Ground transport')], max_length=20)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('facility_code', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('raw_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=30)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('origin', models.CharField(blank=True, max_length=20)),
                ('destination', models.CharField(blank=True, max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('review_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for audit')], default='pending', max_length=20)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.CharField(blank=True, max_length=500)),
                ('parse_error', models.TextField(blank=True)),
                ('source_fingerprint', models.CharField(blank=True, max_length=64)),
                ('edited_by_analyst', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.ingestionbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.tenant')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=30)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.activityrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('analyst', 'Analyst'), ('admin', 'Admin')], default='analyst', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'review_status'], name='core_activi_tenant__d92274_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'source_type'], name='core_activi_tenant__76cd0e_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'is_suspicious'], name='core_activi_tenant__e6a785_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantmembership',
            unique_together={('user', 'tenant')},
        ),
    ]
